### ISSUE TITLE
geting "no meshes to process" error 

### ISSUE THREAD

**Issue by Ali-RS** [kmammou/v-hacd#14]
Hi
I just downloaded v-hacd blender add-on with testVHACD.exe for 64 bit windows.
I load an obj file to blender then select it in blender object mode then in tools--> V-HACD 
i set testVHACD.exe path and click V-HACD button but I got error saying "no meshes to process".
Can you please help?

**Comment by tobyndax** [comment]
Have you tried the different binaries? bin/win32, bin-no-ocl/win32(and 64)? 
(you might not have opencl support for instance).


There is a chance that you are not getting any output from the underlying .exe of the script. 
If you in blender go to Window->"Toggle System Console" and then run VHACD as before. 
In it it should perform a couple of different steps Convex Decomposition, Merge Convex Hulls for example and report back progress. 

If you get an error message (which I suspect you will) it might be more informative.

**Comment by Ali-RS** [comment]
Thanks for fast reply 
yes i did test with bin/win32, win64 , bin-no-ocl/win32 , win64
here is what i get in blender console:

```
Exporting mesh for V-HACD: C:\Users\IDEA\AppData\Local\Temp\Suzanne.off...
Running V-HACD...
C:\Program Files\Blender Foundation\Blender\2.77\testVHACD.exe --input "C:\Users\IDEA\AppData\Local\Temp\Suzanne.off" --resolution 100000 --depth 20 --concavity 0.0025 --planeDownsampling 4 --convexhullDownsampling 4 --alpha 0.05 --beta 0.05 --gamma 0.00125 --pca 0 --mode 0 --maxNumVerticesPerCH 32 --minVolumePerCH 0.0001 --output "C:\Users\IDEA\AppData\Local\Temp\Suzanne.wrl" --log "C:\Users\IDEA\AppData\Local\Temp\Suzanne_log.txt"

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
C:\Users\IDEA\AppData\Local\Temp\Suzanne_log.txt  not created for me!!

**Comment by tobyndax** [comment]
Yeah okay, so if we look at the output. The software (blender or python) seem to have an issue with the space in the C:\Program Files\ ... and thinks the C:\Program part is a program to be executed. For you, moving the testVHACD.exe to somewhere else, where the filepath does not contain a space will fix it for you in the short run. 

In otherwords move testVHACD.exe to somewhere else (like make a new folder under C called VHACD and place the exe there instead, so that the filepath becomes C:\VHACD\testVHACD.exe ) 

Hopefully that will fix your problem for now.

**Comment by Ali-RS** [comment]
thanks it fixed that error. but now getting another error.
I close this issue and will open a new issue for that.
