### ISSUE TITLE
LoadOBJ error in test directory main.cpp 

### ISSUE THREAD

**Issue by teracamo** [kmammou/v-hacd#21]
Error occurs when there are space before  line endings, I recommend changing line 569 of src/test/main.cpp 
to 
```
if (pch && *pch != '\n')
```

**Comment by tobyndax** [comment]
@teracamo It seems you found a problem and found a potential solution as well, great! My suggestion to you is that you fork the repository, change the line in question, verify the fix and then put in a pull request as an solution to your own ticket. Describing, of course, what the pull request aims to fix, and how it fixes it. 

I would say that this is one of the major strengths of github. This is also saves time for the person who is responsible for the repository. While the change might seem small and non-time consuming, due to context switching and similar things, accepting a well formulated pull request is usually, always faster AND in addition while you wait for the original author to incorporate the fix you have your own fork with the fix and can continue to work with a bug-free version.

Best Regards
